Added docker_build_sha

diff --git a/exec_functions b/exec_functions
--- a/exec_functions
+++ b/exec_functions
@@ -7,6 +7,37 @@ set -o pipefail
 
 SEMVER_REGEX='^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-((0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?$'
 
+function docker_build_sha()
+{
+  DOCKERFILE="$1"
+  DOCKER_DIR="$2"
+
+  # Make sure we have valid inputs
+  if [ "$DOCKERFILE" == "" ] ; then
+    echo "Missing Dockerfile argument"
+    return 1
+  fi
+
+  if [ "$DOCKER_DIR" == "" ] ; then
+    echo "Missing docker directory for build"
+    return 1
+  fi
+
+  # Perform the docker build and save the SHA image reference
+  if ! SHA=$(docker build -q -f "$DOCKERFILE" "$DOCKER_DIR") ; then
+    echo "Docker build failed"
+    return 1
+  fi
+
+  # Make sure we have a valid SHA image from the build
+  if [ "$SHA" == "" ] ; then
+    echo "Docker build did not return a SHA image reference"
+    return 1
+  fi
+
+  return 0
+}
+
 function github_release() {
   GITHUB_GENERATE_NOTES='false'
 
